service: ecommerce-auth
frameworkVersion: '2'

provider:
  environment:
    ${file(env.json)}
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  login:
    handler: src/index.login
    events:
      - httpApi: 'POST /login'
  register:
    handler: src/index.register
    events:
      - httpApi: 'POST /register'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
